"use client"

import { createContext, useContext, useState, useEffect, ReactNode } from 'react'

type Language = 'en' | 'ar'
type Direction = 'ltr' | 'rtl'

interface LanguageContextType {
  language: Language
  direction: Direction
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.meals': 'Meals',
    'nav.planner': 'Planner',
    'nav.social': 'Social',
    'nav.profile': 'Profile',
    'nav.strength': 'Strength',
    'nav.exercises': 'Exercises',
    'nav.guide': 'Guide',
    'nav.achievements': 'Achievements',
    
    // Home page
    'home.greeting': 'Hey',
    'home.welcomeBack': 'Welcome back',
    'home.slogans.0': '💪 Train Insane or Remain the Same!',
    'home.slogans.1': '🔥 Your Only Limit is You!',
    'home.slogans.2': '⚡ Stronger Than Yesterday!',
    'home.slogans.3': '🎯 Beast Mode Activated!',
    'home.slogans.4': '💥 Sweat is Fat Crying!',
    'home.slogans.5': '🚀 Champions Train, Losers Complain!',
    'home.slogans.6': '⭐ Pain is Weakness Leaving the Body!',
    'home.calories.title': 'Daily Calorie Target',
    'home.calories.goal': 'Goal',
    'home.calories.consumed': 'Consumed',
    'home.calories.remaining': 'Remaining',
    'home.quickActions': 'Quick Actions',
    'home.logMeal': 'Log Meal',
    'home.startWorkout': 'Start Workout',
    'home.progressPhoto': 'Progress Photo',
    'home.logWater': 'Log Water',
    'home.viewStats': 'View Stats',
    'home.setReminder': 'Set Reminder',
    'home.dailyTips': 'Daily Tips & Insights',
    'home.todaysChallenges': "Today's Challenges",
    'home.weeklyProgress': "This Week's Progress",
    'home.healthDashboard': 'Health Dashboard',
    'home.recommendedWorkouts': 'Recommended for You',
    'home.community': 'Community',
    'home.level': 'Level',
    'home.streak': '7-Day Streak',
    'home.settings': 'Settings',
    'home.mostUsed': 'Most Used',
    'home.active': 'Active',
    'home.weeklyAverage': 'Weekly Average',
    'home.caloriesPerDay': 'calories/day',
    'home.stepsToday': 'Steps Today',
    'home.sleepLastNight': 'Sleep Last Night',
    'home.hydrationGoal': 'Hydration Goal',
    'home.glassesToday': 'glasses today',
    'home.add': 'Add',
    'home.browseAll': 'Browse All',
    'home.perfectForLevel': 'Perfect for your level',
    'home.minutes': 'min',
    'home.calories': 'cal',
    'home.start': 'Start',
    'home.preview': 'Preview',
    'home.shareProgress': 'Share Your Progress',
    'home.connectFitness': 'Connect with other fitness enthusiasts',
    'home.chat': 'Chat',
    'home.share': 'Share',
    'home.good': 'Good',
    'home.of': 'of',
    
    // Meals
    'meals.title': 'Meals & Nutrition',
    'meals.subtitle': 'Track your daily nutrition intake',
    'meals.addMeal': 'Add Meal',
    'meals.search': 'Search for food...',
    'meals.breakfast': 'Breakfast',
    'meals.lunch': 'Lunch',
    'meals.dinner': 'Dinner',
    'meals.snacks': 'Snacks',
    'meals.calories': 'calories',
    'meals.protein': 'Protein',
    'meals.carbs': 'Carbs',
    'meals.fat': 'Fat',
    'meals.setReminder': 'Set Reminder',
    'meals.removeReminder': 'Remove Reminder',
    'meals.add': 'Add',
    'meals.serving': 'serving',
    'meals.servings': 'servings',
    'meals.scanBarcode': 'Scan Barcode',
    'meals.enterManually': 'Enter Manually',
    
    // Exercises
    'exercises.title': 'Exercises & Workouts',
    'exercises.subtitle': 'Track your fitness activities',
    'exercises.startWorkout': 'Start Workout',
    'exercises.viewAll': 'View All',
    'exercises.difficulty': 'Difficulty',
    'exercises.duration': 'Duration',
    'exercises.category': 'Category',
    'exercises.beginner': 'Beginner',
    'exercises.intermediate': 'Intermediate',
    'exercises.advanced': 'Advanced',
    'exercises.cardio': 'Cardio',
    'exercises.strength': 'Strength',
    'exercises.flexibility': 'Flexibility',
    'exercises.complete': 'Complete',
    'exercises.skip': 'Skip',
    
    // Profile
    'profile.title': 'Profile',
    'profile.editProfile': 'Edit Profile',
    'profile.personalInfo': 'Personal Information',
    'profile.fitnessGoals': 'Fitness Goals',
    'profile.statistics': 'Statistics',
    'profile.achievements': 'Achievements',
    'profile.logout': 'Logout',
    'profile.name': 'Name',
    'profile.email': 'Email',
    'profile.age': 'Age',
    'profile.height': 'Height',
    'profile.weight': 'Weight',
    'profile.fitnessLevel': 'Fitness Level',
    'profile.goal': 'Goal',
    'profile.dailyCalories': 'Daily Calories',
    'profile.totalXP': 'Total XP',
    'profile.workoutsCompleted': 'Workouts Completed',
    'profile.currentLevel': 'Current Level',
    
    // Guide
    'guide.title': 'Fitness Guide & Tips',
    'guide.subtitle': 'Learn and improve your fitness journey',
    'guide.search': 'Search articles and tips...',
    'guide.allLevels': 'All Levels',
    'guide.articles': 'Articles',
    'guide.dailyTips': 'Daily Tips',
    'guide.todaysTips': "Today's Tips",
    'guide.allResults': 'All Results',
    'guide.searchResults': 'Search Results',
    'guide.results': 'results',
    'guide.noResults': 'No results found',
    'guide.tryDifferent': 'Try different search terms',
    'guide.featured': 'Featured',
    'guide.featuredArticles': 'Featured Articles',
    'guide.readTime': 'read time',
    'guide.views': 'views',
    'guide.rating': 'rating',
    'guide.nutrition': 'Nutrition',
    'guide.exercise': 'Exercise',
    'guide.wellness': 'Wellness',
    'guide.psychology': 'Psychology',
    'guide.fitnessArticles': 'Fitness Articles',
    'guide.community': 'Fitness Community',
    'guide.members': 'Members',
    'guide.postsToday': 'Posts Today',
    'guide.joinNow': 'Join Now',
    'guide.viewMore': 'View More Tips',
    
    // Challenges & Achievements
    'challenges.stepsChallenge': '10,000 Steps Challenge',
    'challenges.hydrationHero': 'Hydration Hero',
    'challenges.hiitMaster': 'HIIT Master',
    'challenges.reward': 'Reward',
    'challenges.difficulty': 'Difficulty',
    'challenges.easy': 'Easy',
    'challenges.medium': 'Medium',
    'challenges.hard': 'Hard',
    'challenges.timeLeft': 'Time left',
    'challenges.hours': 'hours',
    'challenges.days': 'days',
    'challenges.completed': 'Completed',
    'challenges.collectReward': 'Collect Reward',
    'challenges.viewAll': 'View All Challenges',
    
    // Tips & Categories
    'tips.hydration': 'Hydration Tip',
    'tips.exercise': 'Exercise Tip',
    'tips.recovery': 'Recovery Tip',
    'tips.mental': 'Mental Tip',
    'tips.energy': 'Energy Tip',
    'tips.time': 'Time Tip',
    'tips.nutrition': 'Nutrition',
    'tips.workout': 'Workout',
    'tips.recovery': 'Recovery',
    'tips.psychology': 'Psychology',
    
    // Common
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.close': 'Close',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.complete': 'Complete',
    'common.skip': 'Skip',
    'common.continue': 'Continue',
    'common.confirm': 'Confirm',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.warning': 'Warning',
    'common.info': 'Info',
    'common.comingSoon': 'Feature coming soon!',
    'common.tryAgain': 'Try again',
    'common.viewDetails': 'View Details',
    'common.viewAll': 'View All',
    'common.more': 'More',
    'common.less': 'Less',
    
    // Sidebar
    'sidebar.quickAccess': 'Quick Access',
    'sidebar.quickSettings': 'Quick Settings',
    'sidebar.dietPlans': 'Diet Plans',
    'sidebar.workoutSplits': 'Workout Splits',
    'sidebar.strengthTraining': 'Strength Training',
    'sidebar.progressCompare': 'Progress Compare',
    'sidebar.socialHub': 'Social Hub',
    'sidebar.fitnessGuide': 'Fitness Guide',
    'sidebar.fitnessStats': 'Fitness Stats',
    'sidebar.darkMode': 'Dark Mode',
    'sidebar.notifications': 'Notifications',
    'sidebar.syncStatus': 'Sync Status',
    'sidebar.language': 'Language',
    'sidebar.updateGoals': 'Update Goals',
    'sidebar.signOut': 'Sign Out',
    'sidebar.connected': 'Connected',
    'sidebar.on': 'On',
    
    // Stats and Performance
    'stats.fitnessPerformance': 'Fitness Performance',
    'stats.physical': 'PHYSICAL',
    'stats.nutrition': 'NUTRITION', 
    'stats.discipline': 'DISCIPLINE',
    'stats.mental': 'MENTAL',
    'stats.endurance': 'ENDURANCE',
    'stats.progress': 'PROGRESS',
    'stats.overall': 'Overall',
    'stats.strongestArea': 'Strongest Area',
    'stats.focusArea': 'Focus Area',
    'stats.nextGoal': 'Next Goal',
    'stats.reachLevel': 'Reach Level',
    'stats.weeklyOverview': 'Weekly Overview',
    'stats.dailyCalorieIntake': 'Daily Calorie Intake',
    'stats.monthlySummary': 'Monthly Summary',
    'stats.caloriesBurned': 'Calories burned',
    'stats.totalWorkouts': 'Total workouts',
    
    // Login & Onboarding
    'login.welcome': 'Welcome to FitTracker',
    'login.subtitle': 'Your personal fitness companion',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.signIn': 'Sign In',
    'login.signUp': 'Sign Up',
    'login.signInWithGoogle': 'Sign in with Google',
    'login.tryAsGuest': 'Try as Guest',
    'login.continueAsGuest': 'Continue as Guest',
    
    // More common terms
    'common.water': 'Water',
    'common.steps': 'Steps',
    'common.workouts': 'Workouts',
    'common.today': 'Today',
    'common.thisWeek': 'This Week',
    'common.daily': 'Daily',
    'common.weekly': 'Weekly',
    'common.monthly': 'Monthly',
    'common.level': 'Level',
    'common.goals': 'Goals',
    'common.achievements': 'Achievements',
    'common.stats': 'Stats',
    'common.profile': 'Profile',
    'common.settings': 'Settings',
  },
  ar: {
    // Navigation - التنقل
    'nav.home': 'الرئيسية',
    'nav.meals': 'الوجبات',
    'nav.planner': 'المخطط',
    'nav.social': 'المجتمع',
    'nav.profile': 'الملف الشخصي',
    'nav.strength': 'القوة',
    'nav.exercises': 'التمارين',
    'nav.guide': 'الدليل',
    'nav.achievements': 'الإنجازات',
    
    // Home page - الصفحة الرئيسية
    'home.greeting': 'مرحباً',
    'home.welcomeBack': 'مرحباً بعودتك',
    'home.slogans.0': '💪 تدرب بجنون أو ابق كما أنت!',
    'home.slogans.1': '🔥 حدودك الوحيدة هي أنت!',
    'home.slogans.2': '⚡ أقوى من الأمس!',
    'home.slogans.3': '🎯 تم تفعيل وضع الوحش!',
    'home.slogans.4': '💥 العرق هو دموع الدهون!',
    'home.slogans.5': '🚀 الأبطال يتدربون، الخاسرون يشتكون!',
    'home.slogans.6': '⭐ الألم هو الضعف يخرج من الجسد!',
    'home.calories.title': 'هدف السعرات اليومي',
    'home.calories.goal': 'الهدف',
    'home.calories.consumed': 'المستهلك',
    'home.calories.remaining': 'المتبقي',
    'home.quickActions': 'إجراءات سريعة',
    'home.logMeal': 'تسجيل وجبة',
    'home.startWorkout': 'بدء التمرين',
    'home.progressPhoto': 'صورة التقدم',
    'home.logWater': 'تسجيل الماء',
    'home.viewStats': 'عرض الإحصائيات',
    'home.setReminder': 'تعيين تذكير',
    'home.dailyTips': 'نصائح ورؤى يومية',
    'home.todaysChallenges': 'تحديات اليوم',
    'home.weeklyProgress': 'تقدم هذا الأسبوع',
    'home.healthDashboard': 'لوحة الصحة',
    'home.recommendedWorkouts': 'موصى به لك',
    'home.community': 'المجتمع',
    'home.level': 'المستوى',
    'home.streak': 'سلسلة 7 أيام',
    'home.settings': 'الإعدادات',
    'home.mostUsed': 'الأكثر استخداماً',
    'home.active': 'نشطة',
    'home.weeklyAverage': 'المتوسط الأسبوعي',
    'home.caloriesPerDay': 'سعرة/يوم',
    'home.stepsToday': 'خطوات اليوم',
    'home.sleepLastNight': 'النوم الليلة الماضية',
    'home.hydrationGoal': 'هدف الترطيب',
    'home.glassesToday': 'أكواب اليوم',
    'home.add': 'إضافة',
    'home.browseAll': 'تصفح الكل',
    'home.perfectForLevel': 'مثالي لمستواك',
    'home.minutes': 'دقيقة',
    'home.calories': 'سعرة',
    'home.start': 'ابدأ',
    'home.preview': 'معاينة',
    'home.shareProgress': 'شارك تقدمك',
    'home.connectFitness': 'تواصل مع عشاق اللياقة الآخرين',
    'home.chat': 'دردشة',
    'home.share': 'شارك',
    'home.good': 'جيد',
    'home.of': 'من',
    
    // Meals - الوجبات
    'meals.title': 'الوجبات والتغذية',
    'meals.subtitle': 'تتبع مدخولك الغذائي اليومي',
    'meals.addMeal': 'إضافة وجبة',
    'meals.search': 'البحث عن طعام...',
    'meals.breakfast': 'الإفطار',
    'meals.lunch': 'الغداء',
    'meals.dinner': 'العشاء',
    'meals.snacks': 'الوجبات الخفيفة',
    'meals.calories': 'سعرة حرارية',
    'meals.protein': 'البروتين',
    'meals.carbs': 'الكربوهيدرات',
    'meals.fat': 'الدهون',
    'meals.setReminder': 'تعيين تذكير',
    'meals.removeReminder': 'إزالة التذكير',
    'meals.add': 'إضافة',
    'meals.serving': 'حصة',
    'meals.servings': 'حصص',
    'meals.scanBarcode': 'مسح الباركود',
    'meals.enterManually': 'إدخال يدوي',
    
    // Exercises - التمارين
    'exercises.title': 'التمارين والتدريبات',
    'exercises.subtitle': 'تتبع أنشطتك الرياضية',
    'exercises.startWorkout': 'بدء التمرين',
    'exercises.viewAll': 'عرض الكل',
    'exercises.difficulty': 'الصعوبة',
    'exercises.duration': 'المدة',
    'exercises.category': 'الفئة',
    'exercises.beginner': 'مبتدئ',
    'exercises.intermediate': 'متوسط',
    'exercises.advanced': 'متقدم',
    'exercises.cardio': 'كارديو',
    'exercises.strength': 'قوة',
    'exercises.flexibility': 'مرونة',
    'exercises.complete': 'إكمال',
    'exercises.skip': 'تخطي',
    
    // Profile - الملف الشخصي
    'profile.title': 'الملف الشخصي',
    'profile.editProfile': 'تعديل الملف الشخصي',
    'profile.personalInfo': 'المعلومات الشخصية',
    'profile.fitnessGoals': 'أهداف اللياقة',
    'profile.statistics': 'الإحصائيات',
    'profile.achievements': 'الإنجازات',
    'profile.logout': 'تسجيل الخروج',
    'profile.name': 'الاسم',
    'profile.email': 'البريد الإلكتروني',
    'profile.age': 'العمر',
    'profile.height': 'الطول',
    'profile.weight': 'الوزن',
    'profile.fitnessLevel': 'مستوى اللياقة',
    'profile.goal': 'الهدف',
    'profile.dailyCalories': 'السعرات اليومية',
    'profile.totalXP': 'إجمالي نقاط الخبرة',
    'profile.workoutsCompleted': 'التمارين المكتملة',
    'profile.currentLevel': 'المستوى الحالي',
    
    // Guide - الدليل
    'guide.title': 'دليل اللياقة والنصائح',
    'guide.subtitle': 'تعلم وحسن رحلة اللياقة البدنية',
    'guide.search': 'ابحث عن المقالات والنصائح...',
    'guide.allLevels': 'جميع المستويات',
    'guide.articles': 'مقالات',
    'guide.dailyTips': 'نصائح يومية',
    'guide.todaysTips': 'نصائح اليوم',
    'guide.allResults': 'جميع النتائج',
    'guide.searchResults': 'نتائج البحث',
    'guide.results': 'نتائج',
    'guide.noResults': 'لم يتم العثور على نتائج',
    'guide.tryDifferent': 'جرب مصطلحات بحث مختلفة',
    'guide.featured': 'مميز',
    'guide.featuredArticles': 'المقالات المميزة',
    'guide.readTime': 'وقت القراءة',
    'guide.views': 'مشاهدات',
    'guide.rating': 'التقييم',
    'guide.nutrition': 'التغذية',
    'guide.exercise': 'التمارين',
    'guide.wellness': 'العافية',
    'guide.psychology': 'علم النفس',
    'guide.fitnessArticles': 'مقالات اللياقة',
    'guide.community': 'مجتمع اللياقة',
    'guide.members': 'الأعضاء',
    'guide.postsToday': 'منشورات اليوم',
    'guide.joinNow': 'انضم الآن',
    'guide.viewMore': 'عرض المزيد من النصائح',
    
    // Challenges & Achievements - التحديات والإنجازات
    'challenges.stepsChallenge': 'تحدي 10,000 خطوة',
    'challenges.hydrationHero': 'بطل الترطيب',
    'challenges.hiitMaster': 'خبير الهيت',
    'challenges.reward': 'المكافأة',
    'challenges.difficulty': 'الصعوبة',
    'challenges.easy': 'سهل',
    'challenges.medium': 'متوسط',
    'challenges.hard': 'صعب',
    'challenges.timeLeft': 'الوقت المتبقي',
    'challenges.hours': 'ساعات',
    'challenges.days': 'أيام',
    'challenges.completed': 'مكتمل',
    'challenges.collectReward': 'اجمع المكافأة',
    'challenges.viewAll': 'عرض جميع التحديات',
    
    // Tips & Categories - النصائح والفئات
    'tips.hydration': 'نصيحة الترطيب',
    'tips.exercise': 'نصيحة التمرين',
    'tips.recovery': 'نصيحة التعافي',
    'tips.mental': 'نصيحة نفسية',
    'tips.energy': 'نصيحة الطاقة',
    'tips.time': 'نصيحة الوقت',
    'tips.nutrition': 'التغذية',
    'tips.workout': 'التمرين',
    'tips.recovery': 'التعافي',
    'tips.psychology': 'علم النفس',
    
    // Common - مشتركة
    'common.loading': 'جاري التحميل...',
    'common.search': 'بحث',
    'common.cancel': 'إلغاء',
    'common.save': 'حفظ',
    'common.delete': 'حذف',
    'common.edit': 'تعديل',
    'common.close': 'إغلاق',
    'common.back': 'رجوع',
    'common.next': 'التالي',
    'common.previous': 'السابق',
    'common.complete': 'إكمال',
    'common.skip': 'تخطي',
    'common.continue': 'متابعة',
    'common.confirm': 'تأكيد',
    'common.yes': 'نعم',
    'common.no': 'لا',
    'common.ok': 'موافق',
    'common.error': 'خطأ',
    'common.success': 'نجح',
    'common.warning': 'تحذير',
    'common.info': 'معلومات',
    'common.comingSoon': 'ميزة قادمة قريباً!',
    'common.tryAgain': 'حاول مرة أخرى',
    'common.viewDetails': 'عرض التفاصيل',
    'common.viewAll': 'عرض الكل',
    'common.more': 'المزيد',
    'common.less': 'أقل',
    
    // Sidebar - الشريط الجانبي
    'sidebar.quickAccess': 'وصول سريع',
    'sidebar.quickSettings': 'إعدادات سريعة',
    'sidebar.dietPlans': 'خطط الحمية',
    'sidebar.workoutSplits': 'تقسيمات التمرين',
    'sidebar.strengthTraining': 'تدريب القوة',
    'sidebar.progressCompare': 'مقارنة التقدم',
    'sidebar.socialHub': 'المجتمع',
    'sidebar.fitnessGuide': 'دليل اللياقة',
    'sidebar.fitnessStats': 'إحصائيات اللياقة',
    'sidebar.darkMode': 'الوضع المظلم',
    'sidebar.notifications': 'الإشعارات',
    'sidebar.syncStatus': 'حالة المزامنة',
    'sidebar.language': 'اللغة',
    'sidebar.updateGoals': 'تحديث الأهداف',
    'sidebar.signOut': 'تسجيل الخروج',
    'sidebar.connected': 'متصل',
    'sidebar.on': 'مفعل',
    
    // Stats and Performance - الإحصائيات والأداء
    'stats.fitnessPerformance': 'أداء اللياقة البدنية',
    'stats.physical': 'الجسدي',
    'stats.nutrition': 'التغذية',
    'stats.discipline': 'الانضباط',
    'stats.mental': 'النفسي',
    'stats.endurance': 'التحمل',
    'stats.progress': 'التقدم',
    'stats.overall': 'العام',
    'stats.strongestArea': 'أقوى منطقة',
    'stats.focusArea': 'منطقة التركيز',
    'stats.nextGoal': 'الهدف التالي',
    'stats.reachLevel': 'الوصول للمستوى',
    'stats.weeklyOverview': 'نظرة أسبوعية',
    'stats.dailyCalorieIntake': 'السعرات اليومية',
    'stats.monthlySummary': 'ملخص شهري',
    'stats.caloriesBurned': 'السعرات المحروقة',
    'stats.totalWorkouts': 'إجمالي التمارين',
    
    // Login & Onboarding - تسجيل الدخول والتأهيل
    'login.welcome': 'مرحباً بك في فيت تراكر',
    'login.subtitle': 'رفيقك الشخصي في اللياقة البدنية',
    'login.email': 'البريد الإلكتروني',
    'login.password': 'كلمة المرور',
    'login.signIn': 'تسجيل الدخول',
    'login.signUp': 'إنشاء حساب',
    'login.signInWithGoogle': 'تسجيل الدخول بجوجل',
    'login.tryAsGuest': 'تجربة كضيف',
    'login.continueAsGuest': 'متابعة كضيف',
    
    // More common terms - مصطلحات مشتركة أكثر
    'common.water': 'الماء',
    'common.steps': 'الخطوات',
    'common.workouts': 'التمارين',
    'common.today': 'اليوم',
    'common.thisWeek': 'هذا الأسبوع',
    'common.daily': 'يومي',
    'common.weekly': 'أسبوعي',
    'common.monthly': 'شهري',
    'common.level': 'المستوى',
    'common.goals': 'الأهداف',
    'common.achievements': 'الإنجازات',
    'common.stats': 'الإحصائيات',
    'common.profile': 'الملف الشخصي',
    'common.settings': 'الإعدادات',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en') // Default to English
  const direction: Direction = language === 'ar' ? 'rtl' : 'ltr'

  useEffect(() => {
    const savedLanguage = localStorage.getItem('app_language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'ar')) {
      setLanguageState(savedLanguage)
    } else {
      // If no saved language, default to English
      setLanguageState('en')
      localStorage.setItem('app_language', 'en')
    }
  }, [])

  useEffect(() => {
    document.documentElement.dir = direction
    document.documentElement.lang = language
    document.documentElement.style.fontFamily = language === 'ar' ? 
      '"Noto Sans Arabic", "Cairo", "Tajawal", system-ui, sans-serif' : 
      'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif'
    localStorage.setItem('app_language', language)
  }, [language, direction])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, direction, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}