/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tltkvnvmgwzsmygttnqq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRsdGt2bnZtZ3d6c215Z3R0bnFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTc2MTgsImV4cCI6MjA2OTU5MzYxOH0.-drSK45S4XSW-HbrOjOoUiE882e_7WzJNFrYLmUduJg"